tap "cmacrae/formulae"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"

brew "doctl"
brew "gh"
brew "mas"
brew "neovim"
brew "node"
brew "stow"
brew "tmux"
brew "wget"
brew "yarn"

cask "docker"
cask "mouse-fix"
cask "ngrok"
cask "postman"
cask "slack"
cask "tableplus"
cask "warp"
cask "mimestream"

mas "Xcode", id: 497799835
