tap "cmacrae/formulae"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"

brew "composer"
brew "mas"
brew "node"
brew "stow"
brew "tmux"
brew "wget"
brew "yarn"
brew "koekeishiya/formulae/skhd"

cask "discord"
cask "docker"
cask "postman"
cask "rectangle"
cask "slack"
cask "mimestream"
cask "mouse-fix"
cask "intellij-idea"
cask "spotify"
cask "mouse-fix"

