#!/usr/bin/env zsh

STOW_FOLDERS="config,vim,ssh,zsh"
DOTFILES=$HOME/.dotfiles

pushd $HOME
rm -rf .z*
popd

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
done
popd

