#!/usr/bin/env zsh

STOW_FOLDERS="git,zsh"
DOTFILES=$HOME/.dotfiles

pushd $HOME
if ! which zimfw > /dev/null; then
  echo "Installing zimfw"
  rm -rf .z*
  curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh
  zimfw install
  rm -rf .zimrc .zshrc .zlogin .*.zwc
fi;
popd

pushd $DOTFILES
if ! which brew > /dev/null; then
  echo "Installing homebrew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
  brew update
  brew bundle --no-lock
fi;

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
  echo "Creating symlink for $folder"
  stow $folder
done
popd
