#!/usr/bin/env zsh

STOW_FOLDERS="git,config,vim,ssh,zsh"
DOTFILES=$HOME/.dotfiles

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
  echo "Removing symlink(s) for $folder"
  stow -D $folder
done
popd

pushd $HOME
echo "Installing zimfw"
rm -rf .z*
curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh
rm -rf .zimrc .zshrc .zlogin
popd

pushd $DOTFILES
which -s brew
if [[ $? != 0 ]] ; then
  echo "Installing Homebrew and apps"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  brew bundle install
fi

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
  echo "Creating symlink(s) for $folder"
  stow $folder
done
popd
