set nowrap
set nu
set relativenumber
set nohlsearch
set noerrorbells
set tabstop=2 softtabstop=2
set shiftwidth=2
set smartindent
set expandtab
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch
set backspace=indent,eol,start
set termguicolors
set scrolloff=8
set completeopt=menuone,noinsert,noselect
set signcolumn=yes
set colorcolumn=80
set re=0
set updatetime=100
set nosmd
set autoread
let &t_ut=''

execute pathogen#infect()
syntax on
filetype plugin indent on

let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard', 'find %s -type f']
let g:ctrlp_use_caching = 0

colorscheme gruvbox
set background=dark

source $HOME/.vim/pluginrc/vim-test

